### PR TITLE
All data fix

### LINKED ISSUE #52: Loading of all data is buggy
Clicking on All taxa is not displaying all records  on `master` :( 
This was already buggy on the deployed version at shinyapps where it displays it for a split second and then the DT is blank

### PR DESCRIPTION
**Pull request by disarrayx**
Closes #52 

- [X] All taxa now loads properly
- [X] Download works and is no longer throwing an error due to an erroneous file path

### CODE REVIEW

File: R/generate_taxon_text.R [hunk 1]
```diff
@@ -193,7 +193,7 @@ generate_taxon_portal_links <- function(taxon_info) {
 export_bibtex_for_data <- function(keys, filename, 
     refs = 
         RefManageR::ReadBib(
-        file = "inst/extdata/austraits/sources.bib",
+        file = "inst/extdata/austraits/austraits-5.0.0-lite/sources.bib",
```
Comment (dfalster) [inline R/generate_taxon_text.R:196]: Good catch. But actually, we need to swap out the hard-coded directory to use the directory stored in `data_path` at  https://github.com/traitecoevo/austraits.portal/blob/all-data-fix/R/global.R#L13

File: R/generate_usage_text.R [hunk 2]
```diff
@@ -66,7 +66,7 @@ References
 export_bibtex_for_data <- function(keys, filename, 
     refs = 
         RefManageR::ReadBib(
-        file = "inst/extdata/austraits/sources.bib",
+        file = "inst/extdata/austraits/austraits-5.0.0-lite/sources.bib",
```
Comment (dfalster) [inline R/generate_usage_text.R:69]: as above

File: R/server.R [hunk 3]
```diff
@@ -166,8 +166,10 @@ austraits_server <- function(input, output, session) {
       # Store filtered data into reactive value
       filtered_database(filtered_data)
     } else {
-      # No filters selected
-      filtered_database(NULL)
+      # No filters selected and all taxa is not selected
+      if (input$taxon_rank != "all") {
```
Comment (dfalster) [inline R/server.R:170]: When I have all taxa selected, no data is displaying. Is that result of this change?

**Review by dfalster — CHANGES_REQUESTED** [review]
Nice work @evaluate09 

See couple of requested changes

File: R/server.R (hunk 3 above)
Comment (evaluate09) [reply R/server.R:170]: Huh! That's strange. The initial problem with the data not showing for all taxa was because of the line `filtered_database(NULL)` being called when there were no filters applied (which all taxa couldn't have). The if statement is a fix for this.

It works on my end. I'm not too sure why that's happening but I'll look into it further to see if I can reproduce what you're getting.

File: R/generate_taxon_text.R (hunk 1 above)
Comment (evaluate09) [reply R/generate_taxon_text.R]: I've changed it to `file = paste(data_path, "/sources.bib", sep = "")` now, if that's alright.

File: R/server.R (hunk 3 above)
Comment (dfalster) [reply R/server.R:170]: You're right, it is working. Apologies.

But still some slightly odd behaviour. I think I see what's happening now. If you select a taxa, then click to genus or family, the taxa filter remains. Similarly if you select a genus, then switch to taxa or family. And when you select family, fabaceae always comes up. I think what we want is

1. When you select any filter (all taxa, family, genus, taxa) the other values are forgotten. [these filters were not meant to build on each other but be alternatives]
2. On initial load show family = fabaceae, but from then on don't auto load fabaceae when family is selected.

These could be incorporated into this PR or another.
