### PR TITLE
Apply Filters button and performance optimizations

### LINKED ISSUE #98: Reorder APC state/territory dropdown to alphabetical order
- The APC taxon distribution dropdown should display states/territories in alphabetical order (ACT, NSW, NT, Qld, SA, Tas, Vic, WA) and remove any extra options that aren't Australian states or popular islands.
- States appear in random/default order. Required order: ACT, NSW, NT, Qld, SA, Tas, Vic, WA (alphabetical)

### LINKED ISSUE #99: Remove default/prefilled values in taxonomy filters
- When the app loads or filters are cleared, taxonomy dropdowns (Family, Genus, Taxon name) should be empty with no pre-selected values. Currently they default to specific examples
- Family defaults to "Fabaceae", Genus to "Abutilon", etc.

### LINKED ISSUE #100: Fix URL parameter handling for taxon_type
- URL parameters correctly restore trait names and tabs, but taxon_type always resets to "all taxa" instead of preserving the selected taxon rank (family/genus/taxon_name).
- URL includes taxon selections but taxon_type resets to "all" 
- URL should restore both taxon_type AND the selected taxa

### LINKED ISSUE #101: Reorder data table columns - Family, Genus, Taxon name, Trait name first
- The data table should show the most important taxonomic and trait columns first for better usability.
- What happens: Columns appear in database schema order. Expected to : First 4 columns should be: Family, Genus, Taxon name, Trait name (in that order), followed by remaining columns

### LINKED ISSUE #102: Standardize decimal places in species averages table (2 decimal places)
Species averages table should display mean, median, min, max with consistent decimal formatting (2 places) for better readability. All numeric summary columns show exactly 2 decimal places

### LINKED ISSUE #103: Update Taxon View empty state message
When no taxon is selected, Taxon View should show a helpful message similar to Trait View's formatting. Can remove the temporary technical warning box.

### LINKED ISSUE #104: 2 Apply Filter buttons and fixing space between Custom Filters section
Adding another Apply filters button and there's excess vertical spacing between the two Apply Filter buttons and the Custom Filters section that should be reduced

### LINKED ISSUE #105: Add frozen header row to data table
The data table header (column names) should remain visible when scrolling down through rows so users always know which column they're viewing.

### LINKED ISSUE #108: Fix free text custom filters causing crash with regex() function
Free text custom filters (e.g., searching in measurement_remarks, location_properties) caused white screen crashes when attempting to filter.
The filter application code is using regex(..., ignore_case = TRUE) from stringr, which is an R-side function that cannot be pushed down to DuckDB for lazy evaluation. This is causing the query to fail.

### LINKED ISSUE #109: Add value_metric column to species averages table
### Currently, the species averages table shows separate columns for value_min, value_median, value_max, and unit, which creates clutter and makes it harder to scan numerical trait ranges at a glance.

New value_metric column that displays numerical trait ranges in a compact format: "Min - Median - Max Unit" (e.g., "5.2 - 7.8 - 12.3 cm"). This column should:

- Format values to max 2 decimal places, removing trailing zeros (e.g., 5.00 → 5, 3.50 → 3.5)
- Include unit at the end if present
- Be empty for categorical traits (those without min/median/max values)
- Have a tooltip on the column header explaining the format

The original columns (value_min, value_median, value_max, unit) should be hidden from the display table but remain available in downloads.

### LINKED ISSUE #110: Meaning of numeric shapes in trait view histogram
The trait view histogram displays various geometric shapes (triangles, squares, etc.) alongside the distribution, but their meaning is not documented or explained anywhere in the interface. Users need to understand what these shapes represent to properly interpret the trait distribution visualization

- Add a legend explaining what each shape represents
- Standardize the shapes across different traits if they have inconsistent meanings

### LINKED ISSUE #111: Replace ggplot default colors with custom color scheme
Currently, plots in the portal (trait view histogram, maps, etc.) use ggplot's default blue and orange color scheme.

### PR DESCRIPTION
**Pull request by Pushkalgithub**
### Filter System:

- Added Apply Filters button (top + bottom of sidebar) for manual filter application
- Auto-apply on dataset type switching (species ↔ raw)
- Auto-apply when loading from URL parameters
- Fixed reactive flicker bug (isolated column display reactive)
- Preserved custom filter selections when switching datasets
- Fixed free text filters crashing with DuckDB (replaced regex() with tolower())
- Fixed empty column custom filter bug

### Performance:

- Fixed Smart loading: count rows first, load all if <10k else load 100 rows
- Reduced initial load from 8-15s to 1-2s

### Species Averages Enhancements:

- Added value_metric column (Min - Median - Max Unit format)
- Formatted numeric columns to 2 decimal places without trailing zeros
- Added column header tooltips

### UI/UX Improvements:

- Reordered columns: Family, Genus, Taxon name, Trait name first
- Sticky header for data table
- Taxon view empty state message with instructions
- Removed prefilled taxonomy defaults (all filters start empty)
- Alphabetically ordered APC state dropdown
- Reduced spacing before bottom Apply button

closes #98 
closes #99
closes #100
closes #101
closes #102
closes #103
closes #104
closes #105
closes #108
closes #109
closes #110
closes #111

### CODE REVIEW

**Comment by dfalster** [comment]
Looks very promising @Pushkalgithub ! Worked on my computer. 

Can we move the "apply filters button below the little divider? 

Screenshot 2026-03-09 at 12 41 16

**Comment by Pushkalgithub** [comment]
Screenshot 2026-03-09 135126

I'm getting a strange error in my Codespaces; I'll fix it and push the changes as soon as possible.

**Comment by Pushkalgithub** [comment]
Redeploying with the formatting change!

**Review by dfalster — APPROVED** [review]
Very nice! I tried this locally and works very well.

**Comment by dfalster** [comment]
Great progress!

**Comment by Pushkalgithub** [comment]
@dfalster  Can i squash and merge this branch?

**Comment by dfalster** [comment]
Hi @Pushkalgithub Lizzy has some extra requests to refine. She hasn't sent them yet, but will send them now

File: R/plot_trait_values.R [hunk 1]
```diff
@@ -193,14 +192,14 @@ plot_trait_distribution_beeswarm <- function(data,
...
+    p <- rep("Observation", length(value_type))
 
-    p[grepl("mean", value_type)] <- "_mean" # 16
-    p[grepl("min", value_type)] <- "_min" # 60
-    p[grepl("max", value_type)] <- "_max" # 62
+    p[grepl("mean", value_type)] <- "Mean"
+    p[grepl("min", value_type)] <- "Minimum"
+    p[grepl("max", value_type)] <- "Maximum"
     factor(p, levels = names(my_shapes))
   }
```
Comment (dfalster) [inline R/plot_trait_values.R:204]: Not sure these are working correctly, as no mins and max appearing in the plot. Possibly revert to old symbols. Just need legend added.

Also, "unknown" should be left as "unknown" . "Observation" is too generic a term (they're all observations

**Review by dfalster — APPROVED** [review]
Great work team! At this point looks good.
